name: showslinger
description: ShowSlinger App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_core:
    path: packages/flutter_core
  flutter_widget:
    path: packages/flutter_widget
  flutter_common:
    path: packages/flutter_common
  flutter_network:
    path: packages/flutter_network
  stripe_terminal:
    path: packages/stripe_terminal

  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.2

  json_annotation: ^4.8.0
  carousel_slider: ^4.2.1
  alice: ^0.4.1
  flutter_bloc: ^8.1.3
  chewie: ^1.7.4
  path: ^1.8.3
  freezed_annotation: ^2.4.1


dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.6.1
  flutter_lints: ^3.0.1
  freezed: ^2.4.5

dependency_overrides:
  sensors_plus: ^4.0.2

flutter_gen:
  output: lib/src/generated/
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Semibold.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiboldItalic.ttf
          weight: 500
          style: italic

flutter_intl:
  enabled: true
  main_locale: en
  class_name: Localization
  arb_dir: lib/src/l10n
  output_dir: lib/src/generated