name: flutter_network
description: Flutter Network
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_core:
    path: ../flutter_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  retrofit_generator: ^8.0.0

flutter: