name: flutter_network
description: Flutter Network
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_core:
    path: ../flutter_core
  dio: ^5.4.3+1
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  freezed: ^2.4.5

flutter: