name: flutter_common
description: Flutter Common
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_core:
    path: ../flutter_core
  flutter_widget:
    path: ../flutter_widget
  flutter_network:
    path: ../flutter_network
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.4
  flutter_bloc: ^8.1.3
  camera: ^0.10.5+5
  dropdown_button2: ^2.3.9
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1
  freezed: ^2.4.5


flutter_gen:
  output: lib/src/gen/
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

flutter_intl:
  enabled: true
  main_locale: en
  class_name: Localization
  arb_dir: lib/src/l10n
  output_dir: lib/src/generated